// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiJeFfXNCW1PS9iZVRqOsWyjwnlK-jmQQ',
    appId: '1:788366335277:web:8d6b02b0dffa7fc25147a4',
    messagingSenderId: '788366335277',
    projectId: 'ftoucch-auth',
    authDomain: 'ftoucch-auth.firebaseapp.com',
    storageBucket: 'ftoucch-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOoojKZaW4E_vwG-ngAjXbf4KJEs8YyAE',
    appId: '1:788366335277:android:6eef69badccb70185147a4',
    messagingSenderId: '788366335277',
    projectId: 'ftoucch-auth',
    storageBucket: 'ftoucch-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1sX3xQO8bjQAu-quewRnkN5ttaoOdhXU',
    appId: '1:788366335277:ios:115f39f49a8878a55147a4',
    messagingSenderId: '788366335277',
    projectId: 'ftoucch-auth',
    storageBucket: 'ftoucch-auth.appspot.com',
    iosClientId: '788366335277-t08cbtim59vkcn6m3lph86esuuqhmg1o.apps.googleusercontent.com',
    iosBundleId: 'com.ftoucch.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1sX3xQO8bjQAu-quewRnkN5ttaoOdhXU',
    appId: '1:788366335277:ios:4ec6a6857c8946d65147a4',
    messagingSenderId: '788366335277',
    projectId: 'ftoucch-auth',
    storageBucket: 'ftoucch-auth.appspot.com',
    iosClientId: '788366335277-fk75peb663g691vadm7dsb71737g62c5.apps.googleusercontent.com',
    iosBundleId: 'com.ftoucch.firebaseTutorial.RunnerTests',
  );
}
